server:
  port: 9090

spring:
  #application configuration
  application:
    name: uni-auth

  #datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/users_info_db
    username: root
    password: Vijayalakshmi123@
  #jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


